default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: wizdomiz_development

test:
  <<: *default
  database: wizdomiz_test

production:
  <<: *default
  database: wizdomiz_production
  username: wizdomiz
  password: <%= ENV['WIZDOMIZ_DATABASE_PASSWORD'] %>
